language: ruby
sudo: required
cache:
  bundler: true
  directories:
    - node_modules
rvm:
- 2.5.1
install:
- sudo apt update
- sudo apt install nodejs
- sudo apt install npm
- npm install decktape
before_script:
- bundle
- git submodule init
- git submodule update --init --recursive
script:
- make clean all
